added sentry error logger
surikaterna/slf-sentry pull request #1
Opened 2017-03-24 12:31 UTC by SvenNilsson

2017-03-24 12:38 UTC, spralle commented on lib/slf-sentry.js
> +'use strict';
transpilat skall vara .gitignore? @tbruun

2017-03-24 12:39 UTC, spralle requested changes

2017-03-24 12:39 UTC, spralle commented on lib/slf-sentry.js
> +      console.error(extendedEvent);
bort

2017-03-24 12:39 UTC, spralle commented on lib/slf-sentry.js
> +      console.error(extendedEvent);
med console.error

2017-03-24 12:39 UTC, spralle commented on lib/slf-sentry.js
> +    if (event.level === 'error' && additionlParams.environment) {
Man bör kunna sätta level som man vill skicka till sentry, vi vill kanske skicka både warning och errors tänker jag mig?

2017-03-24 12:39 UTC, spralle commented on lib/slf-sentry.js
> +      console.error(extendedEvent);
och console.log nedan

2017-03-24 12:58 UTC, SvenNilsson commented on lib/slf-sentry.js
> +    if (event.level === 'error' && additionlParams.environment) {
japp det låter som en bra ide, fixar

2017-03-24 12:58 UTC, SvenNilsson commented on lib/slf-sentry.js
> +      console.error(extendedEvent);
ok, varför inte console.error (av ren nyfikenhet)

2017-03-24 13:03 UTC, eaglez commented on lib/slf-sentry.js
> +      console.error(extendedEvent);
krashar i vissa webläsare

2017-03-24 15:39 UTC, SvenNilsson commented on lib/slf-sentry.js
> +      console.error(extendedEvent);
oki

2017-03-25 07:37 UTC, spralle commented on lib/slf-sentry.js
> +      console.error(extendedEvent);
+ att denna skall bara skicka till sentry, logga i konsollen får någon annan göra.

2017-03-25 08:18 UTC, tbruun commented on lib/slf-sentry.js
> +'use strict';
Känns ju rimligt, men möjligen undantag ifall det skall upp på npm? Har sätt flera projekt med .dist.js på git

2017-03-26 10:38 UTC, spralle commented on lib/slf-sentry.js
> +'use strict';
jag tycker .gitignore, men inte i .npmignore dvs den går ändå upp på npm.

2017-03-27 13:21 UTC, spralle requested changes

2017-03-27 13:21 UTC, spralle commented on src/slf-sentry.js
> +      Raven.captureException(extendedEvent);
är verkligen extendedEvent ett exception. Funkar detta?

2017-04-03 14:16 UTC, merged